args:
  batch_size: 256
  epochs: 200
  num_sample_images: 4
  num_workers: 12
  sample_every_n: 5
cae_model:
  cfg:
    checkpoint: null
    latent_dim: 128
    name: resnet
dataset:
  cfg:
    cl_dim: 50
    image_channels: 3
    image_size: 32
    mode: train
    name: cifar100+0-49
    static: false
opt:
  lr: 0.001
  weight_decay: 0
