args:
  batch_size: 256
  epochs: 200
  num_sample_images: 4
  num_workers: 12
  sample_every_n: 5
cae_model:
  cfg:
    checkpoint: null
    latent_dim: 32
    name: small
dataset:
  cfg:
    cl_dim: 5
    image_channels: 1
    image_size: 32
    mode: train
    name: mnist+0-4
    static: false
opt:
  lr: 0.001
  weight_decay: 0
