args:
  batch_size: 256
  beta: 1.0
  epochs: 100
  num_workers: 8
  ood_datasets: null
cls_model:
  cfg:
    checkpoint: null
    method: entropy
    n_featuremaps: 32
    name: resnet
    norm: layernorm
dataset:
  cfg:
    cl_dim: 100
    image_channels: 3
    image_size: 64
    mode: train
    name: tinyimagenet+0-99
    static: false
gan_model:
  cfg:
    conditional: false
    disc_checkpoint: null
    gen_checkpoint: null
    latent_dim: 100
    name: dcgan
opt:
  lr: 0.0002
  min_lr: 1.0e-05
  weight_decay: 0.0002
